version: 3

tasks:
  build:
    cmds:
      - task: build-macos
      - task: build-linux
      - task: build-windows

  build-linux:
    platforms: [linux]
    cmds:
      - yarn tauri build

  build-windows:
    platforms: [windows]
    cmds:
      - yarn tauri build

  build-macos:
    platforms: [darwin]
    cmds:
      - yarn tauri build --target universal-apple-darwin

  dev:
    cmds:
      - task: dev-release

  dev-release:
    cmds:
      - yarn tauri dev --release --features dev-release

  open:
    platforms: [darwin]
    cmd: open ~/Library/Application\ Support/org.neptunefundamentals.wallet
