use std::path::PathBuf;
use std::str::FromStr;
use std::sync::atomic::AtomicBool;
use std::sync::atomic::Ordering;

use anyhow::anyhow;
use anyhow::Context;
use anyhow::Result;
use neptune_primitives::data_directory::DataDirectory;
use neptune_primitives::network::Network;
use neptune_wallet::tasm_lib::prelude::Digest;
use neptune_wallet::tasm_lib::prelude::Tip5;
use neptune_wallet::triton_vm::prelude::BFieldCodec;
use neptune_wallet::twenty_first::bfe_array;
use neptune_wallet::twenty_first::math::b_field_element::BFieldElement;
use serde::de::DeserializeOwned;
use serde::Serialize;
use sqlx::Row;
use sqlx::SqlitePool;
use tokio::sync::Mutex;

use crate::rpc::tls;

mod config_migrate;
pub(crate) mod consts;
pub(crate) mod wallet;

pub(crate) struct Config {
    db: SqlitePool,
    pub(crate) password: Mutex<Option<String>>,
    // the key used to decrypt the wallet secret
    // this key is stored in the config file and encoded with the secret key
    // the secret key is generated by the password
    pub(crate) decrypt_key: Mutex<Vec<u8>>,
    // Set while the wallet is manually locked, so that "locked" is explicit
    // state rather than something inferred from an absent password. Clearing
    // `password` already makes `try_password` answer false, but only as a side
    // effect of the empty-password branch rejecting an encrypted canary. This
    // flag keeps the answer correct if any path repopulates the password, and
    // gives idle auto-lock a state to query.
    locked: AtomicBool,
}

const PASSWORD_TEST: &str = "hello world!";
const PASSWORD_TEST_KEY: &str = "password_test";
const AUTO_LOCK_MINUTES_KEY: &str = "auto_lock_minutes";
const DEFAULT_AUTO_LOCK_MINUTES: u64 = 15;
impl Config {
    pub(crate) async fn new(data_dir: &PathBuf) -> Result<Self> {
        DataDirectory::create_dir_if_not_exists(data_dir).await?;
        let db_path = data_dir.join("config.db");

        let options = sqlx::sqlite::SqliteConnectOptions::new()
            .filename(db_path)
            .create_if_missing(true);

        let pool = sqlx::SqlitePool::connect_with(options)
            .await
            .map_err(|err| anyhow::anyhow!("Could not connect to database: {err}"))?;

        let config = Self {
            db: pool,
            password: Mutex::new(None),
            decrypt_key: Mutex::new(Vec::new()),
            locked: AtomicBool::new(false),
        };

        config.migrate_tables().await?;

        config.set_data_dir(data_dir).await?;

        let log_level = std::env::var("RUST_LOG").unwrap_or("INFO".to_string());
        let _ = config.set_log_level(&log_level).await;

        Ok(config)
    }

    async fn set_data<T: Serialize>(&self, key: &str, value: &T) -> Result<()> {
        let mut conn = self.db.acquire().await?;
        Self::set_data_on(&mut conn, key, value).await
    }

    async fn set_data_on<T: Serialize>(
        conn: &mut sqlx::SqliteConnection,
        key: &str,
        value: &T,
    ) -> Result<()> {
        let data = serde_json::to_vec(value)?;
        sqlx::query("INSERT OR REPLACE INTO config (key, value) VALUES (?1, ?2)")
            .bind(key)
            .bind(data)
            .execute(conn)
            .await
            .context("Failed to insert or replace data")?;
        Ok(())
    }

    async fn get_data<T: DeserializeOwned>(&self, key: &str) -> Result<Option<T>> {
        let row = sqlx::query("SELECT value FROM config WHERE key = ?1")
            .bind(key)
            .fetch_optional(&self.db)
            .await
            .context("Failed to query data")?;

        match row {
            Some(row) => {
                let data: Vec<u8> = row.get(0);
                Ok(Some(serde_json::from_slice(&data)?))
            }
            None => Ok(None),
        }
    }

    pub(crate) async fn set_data_dir(&self, path: &PathBuf) -> Result<()> {
        self.set_data("data_dir", &path).await
    }

    pub(crate) async fn get_data_dir(&self) -> Result<PathBuf> {
        match self.get_data::<PathBuf>("data_dir").await? {
            Some(p) => Ok(p),
            None => Err(anyhow!("data_dir not set")),
        }
    }

    pub(crate) async fn set_wallet_id(&self, id: i64) -> Result<()> {
        self.set_data("wallet_id", &id).await
    }

    pub(crate) async fn get_wallet_id(&self) -> Result<i64> {
        match self.get_data::<i64>("wallet_id").await? {
            Some(v) => Ok(v),
            None => Ok(1),
        }
    }

    pub(crate) async fn set_network(&self, network: Network) -> Result<()> {
        self.set_data("network", &network.to_string()).await
    }

    pub(crate) async fn get_network(&self) -> Result<Network> {
        if let Some(n) = self.get_data::<String>("network").await? {
            return Network::from_str(&n).map_err(|e| anyhow!("{}", e));
        }
        Ok(Network::Main)
    }

    pub(crate) async fn set_disk_cache(&self, enabled: bool) -> Result<()> {
        self.set_data("disk_cache", &enabled).await
    }

    pub(crate) async fn get_disk_cache(&self) -> Result<bool> {
        match self.get_data::<bool>("disk_cache").await? {
            Some(v) => Ok(v),
            None => Ok(true),
        }
    }

    async fn remote_rest_key(&self) -> Result<&str> {
        let network = self.get_network().await?;
        match network {
            Network::Main => Ok("remote_rest"),
            Network::RegTest => Ok("remote_rest_regtest"),
            _ => Ok("remote_rest"),
        }
    }
    pub(crate) async fn set_remote_rest(&self, rest: &String) -> Result<()> {
        let key = self.remote_rest_key().await?;
        self.set_data::<String>(key, rest).await
    }

    pub(crate) async fn get_remote_rest(&self) -> Result<String> {
        let key = self.remote_rest_key().await?;
        Ok(self
            .get_data::<String>(key)
            .await?
            .unwrap_or("https://wallet.neptunefundamentals.org".to_string()))
    }

    pub(crate) async fn decrypt_config(&self, password: &str) -> Result<()> {
        let pass_test = self
            .get_data::<Vec<u8>>(PASSWORD_TEST_KEY)
            .await?
            .context("password not set")?;
        match password {
            "" => {
                if pass_test != PASSWORD_TEST.as_bytes().to_vec() {
                    return Err(anyhow!("password is wrong"));
                }
            }
            _ => {
                let symmetric_key = hash_to_secret_key(password);
                let decrypted = crate::rpc::tls::aes::aes_decode(&symmetric_key, &pass_test)
                    .context("cant decode db")?;
                if decrypted != PASSWORD_TEST.as_bytes() {
                    return Err(anyhow!("password is wrong"));
                }
            }
        };

        {
            let mut password_guard = self.password.lock().await;
            password_guard.replace(password.to_string());
        }

        {
            let decrypt_key = self.get_decrypt_key().await.context("get_decrypt_key")?;
            let mut decrypt_key_guard = self.decrypt_key.lock().await;
            *decrypt_key_guard = decrypt_key;
        }

        Ok(())
    }

    // used to set or change the password
    pub(crate) async fn set_password(&self, old: &str, password: &str) -> Result<()> {
        // make sure config is decrypted, otherwise decrypt_key will be generated and old key will be lost!
        if self.has_password().await? {
            self.decrypt_config(old)
                .await
                .context("failed to decrypt config")?;
        }

        let secret_key = tls::generate_p256_secret().context("generate secret")?;
        let stored_secret_key = match password {
            "" => secret_key.clone(),
            _ => tls::aes::aes_encode(&hash_to_secret_key(password), &secret_key)?,
        };
        let canary = match password {
            "" => PASSWORD_TEST.as_bytes().to_vec(),
            _ => tls::aes::aes_encode(&hash_to_secret_key(password), PASSWORD_TEST.as_bytes())?,
        };

        // The guard stays held until the commit below, so no reader can
        // observe the decrypt key while the rows sealing it are rewritten.
        let mut decrypt_key_guard = self.decrypt_key.lock().await;
        if decrypt_key_guard.is_empty() {
            *decrypt_key_guard = tls::aes::generate_aes_256_key();
        }
        let wallet_secret = tls::aes::aes_encode(&secret_key, &decrypt_key_guard)?;

        // The three rows depend on one another: secret_key opens
        // wallet_secret, and the stored password check must match the
        // password that opens secret_key. One transaction keeps a crash
        // from splitting them, which would leave every stored mnemonic
        // undecryptable.
        let mut tx = self.db.begin().await?;
        Self::set_data_on(&mut tx, "secret_key", &stored_secret_key).await?;
        Self::set_data_on(&mut tx, PASSWORD_TEST_KEY, &canary).await?;
        Self::set_data_on(&mut tx, "wallet_secret", &wallet_secret).await?;
        tx.commit().await?;

        self.password.lock().await.replace(password.to_string());

        Ok(())
    }

    pub(crate) async fn has_password(&self) -> Result<bool> {
        Ok(self.get_data::<Vec<u8>>(PASSWORD_TEST_KEY).await?.is_some())
    }

    /// Mark the wallet locked and forget the password held in memory.
    ///
    /// `decrypt_key` is deliberately left alone: an empty key is the signal
    /// `set_password` uses to generate a fresh one, so clearing it here
    /// would cost the ability to decrypt the wallet secrets.
    pub(crate) async fn lock(&self) {
        self.locked.store(true, Ordering::Relaxed);
        self.password.lock().await.take();
    }

    /// Clear the locked flag. Called once a password has been accepted.
    pub(crate) fn unlock(&self) {
        self.locked.store(false, Ordering::Relaxed);
    }

    pub(crate) fn is_locked(&self) -> bool {
        self.locked.load(Ordering::Relaxed)
    }

    /// Creates the wallet encryption keys when none exist yet, so an account
    /// can be created before a password is chosen. A no-op once a secret key
    /// is stored.
    pub(crate) async fn ensure_wallet_keys(&self) -> Result<()> {
        if self.get_data::<Vec<u8>>("secret_key").await?.is_some() {
            return Ok(());
        }

        let secret_key = tls::generate_p256_secret().context("generate secret")?;
        // The password is normally still unset here; the empty password
        // stores the key unencrypted until set_password re-wraps everything
        // under the real one.
        let stored_secret_key = {
            let mut password = self.password.lock().await;
            let password = password.get_or_insert_with(String::new);
            if password.is_empty() {
                secret_key.clone()
            } else {
                tls::aes::aes_encode(&hash_to_secret_key(password), &secret_key)?
            }
        };

        // Same discipline as set_password: the guard stays held until the
        // commit below, and the two rows land in one transaction, so a crash
        // cannot store a secret_key without the wallet_secret it opens.
        let mut decrypt_key_guard = self.decrypt_key.lock().await;
        if decrypt_key_guard.is_empty() {
            *decrypt_key_guard = tls::aes::generate_aes_256_key();
        }
        let wallet_secret = tls::aes::aes_encode(&secret_key, &decrypt_key_guard)?;

        let mut tx = self.db.begin().await?;
        Self::set_data_on(&mut tx, "secret_key", &stored_secret_key).await?;
        Self::set_data_on(&mut tx, "wallet_secret", &wallet_secret).await?;
        tx.commit().await?;

        Ok(())
    }

    // secret_key is encoded with the password, it will be changed when the password is changed
    // it is not stable to use it as the key to decrypt the wallet secret, but can be used to validate access via rpc
    pub(crate) async fn get_secret_key(&self) -> Result<Vec<u8>> {
        let encrypted_secret = self
            .get_data::<Vec<u8>>("secret_key")
            .await
            .context("cant read db")?
            .context("secret not set!")?;

        match self
            .password
            .lock()
            .await
            .clone()
            .ok_or(anyhow!("no password set!"))?
            .as_str()
        {
            "" => Ok(encrypted_secret),
            str => {
                let symmetric_key = hash_to_secret_key(str);
                let decrypted = tls::aes::aes_decode(&symmetric_key, &encrypted_secret)
                    .context("decode secret key")?;
                Ok(decrypted)
            }
        }
    }

    async fn get_decrypt_key(&self) -> Result<Vec<u8>> {
        let symmetric_key = self.get_secret_key().await.context("get secret key")?;

        let encoded = self
            .get_data::<Vec<u8>>("wallet_secret")
            .await?
            .context("wallet secret not set")?;

        let decoded =
            tls::aes::aes_decode(&symmetric_key, &encoded).context("decode decrypt_key")?;
        Ok(decoded)
    }

    /// Stored here rather than in the frontend so the choice survives a reset
    /// of the webview's local storage.
    pub(crate) async fn set_auto_lock_minutes(&self, minutes: u64) -> Result<()> {
        self.set_data::<u64>(AUTO_LOCK_MINUTES_KEY, &minutes).await
    }

    pub(crate) async fn get_auto_lock_minutes(&self) -> Result<u64> {
        Ok(self
            .get_data::<u64>(AUTO_LOCK_MINUTES_KEY)
            .await?
            .unwrap_or(DEFAULT_AUTO_LOCK_MINUTES))
    }

    pub(crate) async fn set_log_level(&self, level: &str) -> Result<()> {
        self.set_data::<String>("log_level", &level.to_string())
            .await
    }

    pub(crate) async fn get_log_level(&self) -> Result<Option<String>> {
        self.get_data::<String>("log_level").await
    }
}

/// Returns a 256-bit secret key derived from the string through hashing.
fn hash_to_secret_key(str: &str) -> Vec<u8> {
    const NUM_ROUNDS: usize = 100;
    let salt = Digest::new(bfe_array![
        0xECA2F4D64CA79464u64,
        0x2B13424E6F75CAF4u64,
        0u64,
        0u64,
        0u64
    ]);

    let input = BFieldCodec::encode(&str.as_bytes().to_vec());
    let input = Tip5::hash(&input);
    let mut state = Tip5::hash_pair(input, Tip5::hash(&salt));
    for _ in 0..NUM_ROUNDS {
        state = Tip5::hash_pair(input, state);
    }

    let state = state.values();
    let key256_bits = state
        .into_iter()
        .flat_map(|elem| elem.value().to_be_bytes())
        .take(32);

    key256_bits.collect()
}

#[cfg(test)]
mod tests {
    use itertools::Itertools;
    use tracing_test::traced_test;

    use super::*;
    use crate::tests::unit_test_dir;

    #[tokio::test]
    #[traced_test]
    async fn auto_lock_minutes_roundtrip() {
        let config = Config::new(&unit_test_dir()).await.unwrap();

        assert_eq!(
            DEFAULT_AUTO_LOCK_MINUTES,
            config.get_auto_lock_minutes().await.unwrap()
        );

        // 0 is "never", so it must read back as stored rather than falling
        // through to the default the way an absent value does.
        config.set_auto_lock_minutes(0).await.unwrap();
        assert_eq!(0, config.get_auto_lock_minutes().await.unwrap());

        config.set_auto_lock_minutes(5).await.unwrap();
        assert_eq!(5, config.get_auto_lock_minutes().await.unwrap());
    }

    fn devnet_mnemonic() -> Vec<String> {
        vec![
            "margin", "quality", "divorce", "tuition", "notable", "squirrel", "park", "jar", "end",
            "beauty", "attend", "cliff", "media", "letter", "private", "decline", "absurd",
            "uniform",
        ]
        .into_iter()
        .map(|x| x.to_string())
        .collect()
    }

    #[tokio::test]
    #[traced_test]
    async fn password_change_preserves_wallet_secrets() {
        let config = Config::new(&unit_test_dir()).await.unwrap();
        config.set_password("", "first password").await.unwrap();

        let sealed = config.mnemonic_to_secret(devnet_mnemonic()).await.unwrap();

        config
            .set_password("first password", "second password")
            .await
            .unwrap();

        // A mnemonic sealed before the change must survive the rekey.
        assert_eq!(
            devnet_mnemonic(),
            config.secret_to_mnemonic(sealed).await.unwrap()
        );
        assert!(config.decrypt_config("second password").await.is_ok());
        assert!(config.decrypt_config("first password").await.is_err());
    }

    #[tokio::test]
    #[traced_test]
    async fn password_change_rejects_wrong_old_password() {
        let config = Config::new(&unit_test_dir()).await.unwrap();
        config.set_password("", "right password").await.unwrap();
        let sealed = config.mnemonic_to_secret(devnet_mnemonic()).await.unwrap();

        assert!(config
            .set_password("wrong password", "new password")
            .await
            .is_err());

        // Nothing changed: the old password still opens everything.
        assert!(config.decrypt_config("right password").await.is_ok());
        assert_eq!(
            devnet_mnemonic(),
            config.secret_to_mnemonic(sealed).await.unwrap()
        );
    }

    #[tokio::test]
    #[traced_test]
    async fn add_wallet_before_password() {
        const PASSWORD: &str = "chosen after the account";
        let config = Config::new(&unit_test_dir()).await.unwrap();

        // First-run order: the account exists before any password does.
        let id = config
            .add_wallet("first", devnet_mnemonic(), Default::default())
            .await
            .unwrap();
        assert!(!config.has_password().await.unwrap());

        config.set_password("", PASSWORD).await.unwrap();

        // The mnemonic stored before the password must survive the re-wrap.
        assert_eq!(
            devnet_mnemonic(),
            config.get_wallet_mnemonic(id).await.unwrap()
        );
        assert!(config.decrypt_config(PASSWORD).await.is_ok());
    }

    #[tokio::test]
    #[traced_test]
    async fn mnemonic_roundtrip() {
        const PASSWORD: &str = "Once upon a midnight dreary";
        let config_path = unit_test_dir();
        let config = Config::new(&config_path).await.unwrap();

        config.set_password("", PASSWORD).await.unwrap();
        assert!(config.decrypt_config(PASSWORD).await.is_ok());

        let devnet_mnemonic = vec![
            "margin", "quality", "divorce", "tuition", "notable", "squirrel", "park", "jar", "end",
            "beauty", "attend", "cliff", "media", "letter", "private", "decline", "absurd",
            "uniform",
        ]
        .into_iter()
        .map(|x| x.to_string())
        .collect_vec();

        let secret = config
            .mnemonic_to_secret(devnet_mnemonic.clone())
            .await
            .unwrap();
        let mnemonic_again = config.secret_to_mnemonic(secret).await.unwrap();

        assert_eq!(devnet_mnemonic, mnemonic_again);
    }
}
